title: "Metabase | Business Intelligence, Dashboards, and Data Visualization"
email: info@metabase.com
description: "Metabase business intelligence, dashboards, and data visualization tools. Dig deeper into your data with open source, no SQL tools for data visualization."
url: "https://www.metabase.com"
twitter_username: metabase
github_username: metabase
highlighter: rouge
markdown: kramdown
default_social_image: /images/twitter/default.png
redcarpet:
  extensions:
    [no_intra_emphasis, fenced_code_blocks, autolink, tables, with_toc_data]
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
  - jekyll_include_plugin
  - jekyll_dirname_payload_plugin
jekyll_include_plugin:
  snippet_prefix: ''
sass:
  sass_dir: _sass
  style: expanded
permalink: "/blog/:title"
webrick:
  headers:
    X-Frame-Options: deny
    Content-Security-Policy: frame-ancestors 'none'
latest_version: v0.50.31
latest_enterprise: v1.50.31
docs_version: v0.50
release_branch: release-x.50.x
available_versions:
  - master
  - v0.46
  - v0.47
  - v0.48
  - v0.49
  - v0.50
  - v0.51
  - v0.52
collections:
  blog-authors:
    output: true
  case-studies:
    output: true
  cloud:
    output: true
  community-posts:
    output: true
  dashboards:
    output: true
  data-sources:
    output: true
  data-stack-report-2023:
    output: true
  enterprise:
    output: true
  events:
    output: true
  features:
    output: true
  gallery:
    output: true
  get-demo:
    output: true
  glossary:
    output: true
  help:
    output: true
  learn:
    output: true
  legal:
    output: true
  license:
    output: true
  lp:
    output: true
  partners:
    output: true
  pricing:
    output: true
  product:
    output: true
  examples:
    output: true
  releases:
    output: true
  sales:
    output: true
  startup-guide:
    output: true
  start:
    output: true
  talk-to-a-person:
    output: true
  troubleshooting:
    output: true
  upgrade:
    output: true
  docs:
    output: true
defaults:
  - scope:
      type: case-studies
    values:
      layout: case_study
      permalink: /:collection/:path
  - scope:
      type: cloud
    values:
      layout: cloud_docs
      permalink: /:collection/:path
  - scope:
      type: community-posts
    values:
      layout: community_post
      permalink: /:collection/:path
  - scope:
      type: dashboards
    values:
      layout: dashboards
      permalink: /:collection/:path
  - scope:
      type: data-sources
    values:
      layout: data_source
      permalink: /:collection/:path
  - scope:
      type: data-stack-report-2023
    values:
      layout: default
      permalink: /:collection/:path
  - scope:
      type: enterprise
    values:
      layout: default
      permalink: /:collection/:path
  - scope:
      type: events
      permalink: /:collection/:path
    values:
      layout: event
      permalink: /:collection/:path
  - scope:
      type: features
    values:
      layout: feature
      permalink: /:collection/:path
  - scope:
      type: gallery
    values:
      layout: gallery
      permalink: /:collection/:path
  - scope:
      type: get-demo
    values:
      layout: landing-page
      permalink: /:collection/:path
  - scope:
      type: glossary
    values:
      layout: glossary-entry
      permalink: /:collection/:path
  - scope:
      type: help
    values:
      layout: default
      permalink: /:collection/:path
  - scope:
      type: learn
    values:
      layout: learn_article
      permalink: /:collection/:path
  - scope:
      type: legal
    values:
      layout: legal
      permalink: /:collection/:path
  - scope:
      type: license
    values:
      layout: centered_content
      permalink: /:collection/:path
  - scope:
      type: lp
    values:
      layout: landing-page
      permalink: /:collection/:path
  - scope:
      type: partners
    values:
      layout: partner
      permalink: /:collection/:path
  - scope:
      type: pricing
    values:
      layout: pricing
      permalink: /:collection/:path
  - scope:
      type: product
    values:
      layout: default
      permalink: /:collection/:path
  - scope:
      type: examples
    values:
      layout: example
      permalink: /:collection/:path
  - scope:
      type: releases
    values:
      layout: release
      permalink: /:collection/:path
  - scope:
      type: sales
    values:
      layout: default_bare
      permalink: /:collection/:path
  - scope:
      type: start
    values:
      layout: default
      permalink: /:collection/:path
  - scope:
      type: startup-guide
    values:
      layout: startup-guide
      permalink: /:collection/:path
  - scope:
      type: talk-to-a-person
    values:
      layout: default_bare
      permalink: /:collection/:path
  - scope:
      type: troubleshooting
    values:
      layout: default
      permalink: /:collection/:path
  - scope:
      type: upgrade
    values:
      layout: default
      permalink: /:collection/:path
  - scope:
      type: docs
    values:
      layout: new-docs
      permalink: /:collection/:path
exclude:
  - _docs
  - _case-studies
  - _cloud
  - _cloud-docs
  - _community_posts
  - _data-sources
  - _drafts
  - _enterprise
  - _events
  - _examples
  - _features
  - _gallery
  - _glossary
  - _help
  - _learn
  - _legal
  - _license
  - _partners
  - _posts
  - _releases
  - _sales
  - _start
  - _startup-guide
  - _troubleshooting
  - _upgrade
  - _site
  - images/0*
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - webpack.config.js
  - node_modules
  - bower_components
  - .idea
  - .sass-cache
  - package.json
  - package-lock.json
  - yarn.lock
  - s3_website.template.yml
  - src
  - script
  - lib
  - spec
  - vendor
  - typescript
per_incident_support: 350
STRIPE_PUBLISHABLE_API_KEY: pk_test_cW4xg5Kw7s6pIcxjaha5GJeP
search_autofocus:
  - README
