#!/usr/bin/env node
const program = require("commander");
const yaml = require("yamljs");
const fs = require("fs");
const path = require("path");
const { addFrontmatter } = require("../lib/frontmatter.js");
const fetchDocs = require("../lib/fetch-docs.js");
const { moveCloudDocsToLatest } = require("../lib/cloud.js");
const { squashVersion, updateRedirectsAndLinks } = require("../lib/utils.js");

var settings = {
  latest: false,
  version: "master",
  finalDir: "_docs",
  newDir: undefined,
  config: "_config.yml",
  update: false,
};

program
  .option("-l, --latest") // copy docs into _docs/latest
  .option("-s, --set-version <version>") // Specify target directory and version
  .option("-u, --update") // Download docs from current release_branch
  // When set, we grab the tarball for this branch
  .option("-b, --source-branch <dir>");

program.parse(process.argv);

const options = program.opts();

if (options.sourceBranch) {
  settings.branchName = options.sourceBranch
}

// When running script with --update flag, fetch-docs won't update the latest_version in the config.
// Useful when you've backported a docs PR and you want to update the docs on the website.
if (options.update) {
  settings.update = true;
}

// If no branch is specified, use the current release branch
if (program.args.length > 0 && program.args[0][0] != "-") {
  settings.version = program.args[0];
}

const config = yaml.load("_config.yml");
// if we're updating, use the current release branch.
if (settings.update) {
  settings.version = config.release_branch;
}

// When using the --latest flag, the most recent version will also be copied to the latest directory,
// clobbering whatever was there.
if (options.latest) {
  settings.latest = true;
}

// We can tag a branch. So if you download from branch release-x.41.x
// But you want docs to specify a version, tag it v0.41.2 or whatever.
if (options.setVersion) {
  settings.setVersion = options.setVersion;
  console.log("Version set to", options.setVersion);
}

// If no repoDir is specified, download and extract a tarball. That will not
// work for branch previews, so we usually (todo: always?) need to setup the
// repo before running this script.
if (options.repoDir) {
  console.log("Metabase docs data downloaded already in:", options.repoDir);
  settings.newDir = options.repoDir;
} else {
  console.log("Downloading metabase docs data from branch:", settings.version);
}

if (!settings.version.match(/^v[0-9]+\./)) {
  console.warn("WARNING: version is not in the canonical form (e.g. v0.44.3)");
}

console.log("Settings: ", settings);

// set settings.newDir to skip the download step
// if we already have 'downloaded' it.

fetchDocs(settings)
  .then(() => {
    const version = settings.update ? config.docs_version : settings.setVersion;

    console.log("Squashing version", version);
    const docsVersion = squashVersion(version);
    console.log("docsVersion", docsVersion);

    if (settings.latest) {
      // Before we update frontmatter for our latest (search-engine indexed) docs
      // We should move the cloud docs into latest
      moveCloudDocsToLatest();
      updateRedirectsAndLinks(`_docs/latest`);
      const frontmatter = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../lib/latest-frontmatter.json"), 'utf8'));
      console.log("Adding frontmatter to cloud docs\n", frontmatter)
      addFrontmatter("_docs/latest", frontmatter);
    }
    updateRedirectsAndLinks(`_docs/${docsVersion}/`);
    console.log("Done! Docs are in " + settings.finalDir + (settings.latest ? " and /latest." : "."));
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
