#!/bin/sh
# usage: script/links
#
# Check for broken links

#!/bin/bash
TARGET="${1:-_site}" #default to _site

bundle exec htmlproofer "$TARGET" \
       --check-opengraph \
       --check-html \
       --assume-extension \
       --disable-external \
       --allow_hash_href \
       --file-ignore '/\/community\//,/\/start\//,/\/plans\//,/\/pricing\//,/\/docs\/v.*/,/\/docs\/master/,/\/home\/new\//,/\/docs\/latest\/(contributing|faq)\.html/,/.*running-metabase-on-elastic-beanstalk.*/' \
       --url-ignore "/docs/latest/api/" \
       --checks-to-ignore HtmlCheck \
       --empty-alt-ignore true
