#!/bin/sh
# usage: script/lint [--verbose]
# Lints the _learn directory
# See script/_linter/

npm run lint-learn &&
    npm run lint-learn-data &&
    npm run frontMatter-blog &&
    npm run frontMatter-glossary
