#!/bin/sh
# usage: script/server

# Clear the existing site
rm -rf _site

# Run the jekyll server
JEKYLL_ENV=development bundle exec jekyll serve --baseurl '' --watch --incremental --config _config.dev.yml
