#!/usr/bin/env node

var fs = require('fs')
var request = require('request')

var token = process.env.METABASE_ACCESS_TOKEN
var options = {
  url: 'https://api.github.com/repos/metabase/metabase/releases',
  json: true,
  headers: {
    'user-agent': 'Metabase',
    'Authorization': 'token ' + token
  }
}

request(options, function (error, response, body) {
  if (error) return console.log(error)
  if (response.statusCode == 200) {
    body.forEach(function (release) {
      delete release.assets
      delete release.author
    })
    fs.writeFileSync('_data/releases.json', JSON.stringify(body, null, 2))
  }
})
