name: Jekyll site CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # `refresh-docs.yml` cannot trigger workflows with its `GITHUB_TOKEN` except through an explicit `workflow_dispatch`
  # (cf. https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow):
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby # uses version from .ruby-version
        uses: ruby/setup-ruby@d5fb7a202fc07872cb44f00ba8e6197b70cb0c55 # v1.179.0
        with:
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install packages
        run: yarn

      - name: "Lint markdown"
        run: "yarn lint-markdown"

      - name: "Lint styles"
        run: "yarn lint-styles"

      - name: "Validate links"
        run: "yarn lint-links"

      - name: "Lint scripts"
        run: "yarn lint-scripts"

      - name: Build Jekyll Site
        env:
          JEKYLL_ENV: staging
          NODE_ENV: production
        run: "script/build"

      - name: "Check all links"
        run: "script/links"
