name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby # uses version from .ruby-version
        uses: ruby/setup-ruby@d5fb7a202fc07872cb44f00ba8e6197b70cb0c55 # v1.179.0
        with:
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll Site
        env:
          JEKYLL_ENV: staging
        run: "script/build"

      - name: "Check all links"
        id: htmlproofer
        run: "script/links > ./.github/links-to-fix.md"

      - name: Create Issue From File
        if: steps.htmlproofer.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./.github/links-to-fix.md
          assignees: jeff-bruemmer

