name: Process Docs Changes

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Which `metabase/metabase` branch triggered this workflow
        required: true
        type: string

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered for branch ${{ inputs.branch_name }}"
