# The trigger is on the main repo, see
# https://github.com/metabase/metabase/blob/master/.github/workflows/release.yml

name: Release-triggered update
on:
  repository_dispatch:
    types:
      - trigger-docs-update

jobs:
  update:
    runs-on: ubuntu-20.04
    if: startsWith(github.event.client_payload.version, 'v0.')   # EE does not need docs update
    timeout-minutes: 20
    steps:
      - run: echo "Release-triggered -> updating docs for version ${{ github.event.client_payload.version }}..."

      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Create a pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "metabase-bot@metabase.com"
          git config user.name "Metabase Release bot"

          UPDATE_BRANCH="release-update-docs-${{ github.event.client_payload.version }}"
          git checkout -b ${UPDATE_BRANCH}

          ./script/docs ${{ github.event.client_payload.version }} --latest  --set-version${{ github.event.client_payload.version }}
          ./script/cloud
          git add .
          git commit -m "Release ${{ github.event.client_payload.version }}: update docs"
          git push --force origin ${UPDATE_BRANCH}

          gh pr create \
            --title "Update docs to ${{ github.event.client_payload.version }}" \
            --head "${UPDATE_BRANCH}" \
            --body "Automated docs version update"
      - name: Validate links
        run: "yarn lint-links"
