name: Update Changelog

on:
  repository_dispatch:
    types: ['update-changelog', 'add-changelog']

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NEW_VERSION: ${{ github.event.client_payload.version }}
      MAJOR_VERSION: ${{ github.event.client_payload.majorVersion }}
      TEXT: ${{ github.event.client_payload.text }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: _releases
      - name: update changelog
        if: github.event.action == 'update-changelog'
        run: | # bash
          git config --global user.email "metabase-bot@metabase.com"
          git config --global user.name "Metabase bot"

          BRANCH_NAME="update-changelog-$NEW_VERSION"

          git checkout -b $BRANCH_NAME
          cd _releases/changelog

          PLACEHOLDER="<span id=\"next-placeholder\" \/>"

          sed -i "s/${PLACEHOLDER}/${PLACEHOLDER}\n\n${TEXT}\n\n/g" "$MAJOR_VERSION.md"

          git add $MAJOR_VERSION.md
          git commit -m "Update changelog for $NEW_VERSION"
          git push -f -u origin $BRANCH_NAME

      - name: Open PR
        run: | # bash
          gh pr create \
            --title "Changelog update for version $NEW_VERSION" \
            --body "Update changelog for $NEW_VERSION" \
            --reviewer "alexyarosh" \
            --assignee "alexyarosh"

