name: Update docs - 61
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

run-name: Nightly docs update - 61

jobs:
  update-docs:
    uses: ./.github/workflows/update-docs-base-bun.yml
    with:
      source_branch: "release-x.61.x"
      target_branch: "release-x.61.x"
      annotation: "nightly"
      run_name: "Nightly docs build - 61"
    secrets:
      METABASE_AUTOMATION_USER_TOKEN: ${{ secrets.METABASE_AUTOMATION_USER_TOKEN }}
