name: Update docs - 63
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

run-name: Nightly docs update - 63

jobs:
  update-docs:
    uses: ./.github/workflows/update-docs-base-bun.yml
    with:
      source_branch: "release-x.63.x"
      target_branch: "release-x.63.x"
      annotation: "nightly"
      run_name: "Nightly docs build - 63"
    secrets:
      METABASE_AUTOMATION_USER_TOKEN: ${{ secrets.METABASE_AUTOMATION_USER_TOKEN }}

