name: Update docs
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  update-released-docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Create a pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "metabase-bot@metabase.com"
          git config user.name "Metabase Docs bot"

          UPDATE_BRANCH="update-docs-${{ github.event.inputs.version }}"
          git checkout -b ${UPDATE_BRANCH}

          ./script/docs ${{ github.event.inputs.branch }} --latest  --set-version ${{ github.event.inputs.version }}
          ./script/docs master --set-version master
          git add .
          git commit -m "Update docs to ${{ github.event.inputs.version }}"
          git push --force origin ${UPDATE_BRANCH}

          hub pull-request -F- <<<"Update docs to ${{ github.event.inputs.version }}"
      - name: Validate links
        run: "yarn lint-links"
