name: Update Docs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

run-name: Nightly docs update | master

jobs:
  update-docs:
    uses: ./.github/workflows/update-docs-base-bun.yml
    with:
      source_branch: "master"
      target_branch: "master"
      annotation: "nightly"
      run_name: "Nightly docs build for master"
    secrets:
      METABASE_AUTOMATION_USER_TOKEN: ${{ secrets.METABASE_AUTOMATION_USER_TOKEN }}
